- name: Secure Install | Remove anonymous mysql user
  mysql_user: login_user={{mysql_login_user}}
              login_password={{mysql_login_password}}
              name=""
              state=absent
 
- name: Secure Install | Remove mysql test database
  mysql_db: login_user={{mysql_login_user}}
            login_password={{mysql_login_password}}
            name=test
            state=absent
